### ISSUE TITLE
Just an issue... Can't run fishtest and yada-yada...

### ISSUE THREAD

**Issue by d3vv** [glinscott/fishtest#200]
$ python2.7 fishtest/worker/worker.py
Worker version 62 connecting to http://tests.stockfishchess.org:80
Will fetch task soon...
Verifying signature of stockfish ...

Exception running games:
Traceback (most recent call last):
  File "fishtest/worker/worker.py", line 91, in worker
  File "/home/dew/fishtest/worker/games.py", line 419, in run_games
    base_nps = verify_signature(new_engine, run['args']['new_signature'], remote, result, games_concurrency * threads)
  File "/home/dew/fishtest/worker/games.py", line 84, in verify_signature
    if int(bench_sig) != int(signature):
ValueError: invalid literal for int() with base 10: ''
Task exited

**Comment by Stefano80** [comment]
Is this solved?

**Comment by d3vv** [comment]
affirmative
