### ISSUE TITLE
an issue on clean install: global name 'book' is not defined

### ISSUE THREAD

**Issue by marrco** [glinscott/fishtest#204]
I guess this is due to one of the latest script cleanups
https://groups.google.com/forum/#!topic/fishcooking/7lfF0pDRCw8

I think it's better to report it here.

**Comment by ppigazzini** [comment]
@Stefano80 bug replicated with a clean install of the worker on windows and linux. Reverting locally the PR https://github.com/glinscott/fishtest/pull/149 solved the problem.

**Comment by ppigazzini** [comment]
Bugged PR reverted with this https://github.com/glinscott/fishtest/pull/207

**Comment by marrco** [comment]
not fixed atm  ( 8am cest)
```

g++ -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-use -fno-peel-loops -fno-tracer -pedantic -Wextra -Wshadow -m64 -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o syzygy/tbprobe.o syzygy/tbprobe.cpp
g++ -o stockfish benchmark.o bitbase.o bitboard.o endgame.o evaluate.o main.o material.o misc.o movegen.o movepick.o pawns.o position.o psqt.o search.o thread.o timeman.o tt.o uci.o ucioption.o syzygy/tbprobe.o -lgcov -m64 -Wl,--no-as-needed -lpthread -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-use -fno-peel-loops -fno-tracer -pedantic -Wextra -Wshadow -m64 -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto
make[2]: Leaving directory '/tmp/tmp4o0WoG/31m059-Stockfish-9953bff/src'
make[1]: Leaving directory '/tmp/tmp4o0WoG/31m059-Stockfish-9953bff/src'

Step 4/4. Deleting profile data ...
make ARCH=x86-64-modern COMP=gcc profileclean
make[1]: Entering directory '/tmp/tmp4o0WoG/31m059-Stockfish-9953bff/src'
make[1]: Leaving directory '/tmp/tmp4o0WoG/31m059-Stockfish-9953bff/src'

Exception running games:
Traceback (most recent call last):
  File "fishtest-master/worker/worker.py", line 91, in worker
  File "/home/fishtest/fishtest-master/worker/games.py", line 401, in run_games
    cleanup(book, testing_dir)
  File "/home/fishtest/fishtest-master/worker/games.py", line 100, in cleanup
    if not os.path.exists(os.path.join(testing_dir, book)):
NameError: global name 'book' is not defined
Task exited

```
