### ISSUE TITLE
global name 'book' is not defined: still getting that error

### ISSUE THREAD

**Issue by marrco** [glinscott/fishtest#209]
Issue https://github.com/glinscott/fishtest/issues/204 still not fixed for me (3/29 - 8am cest)

```
g++ -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-use -fno-peel-loops -fno-tracer -pedantic -Wextra -Wshadow -m64 -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o timeman.o timeman.cpp
g++ -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-use -fno-peel-loops -fno-tracer -pedantic -Wextra -Wshadow -m64 -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o tt.o tt.cpp
g++ -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-use -fno-peel-loops -fno-tracer -pedantic -Wextra -Wshadow -m64 -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o uci.o uci.cpp
g++ -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-use -fno-peel-loops -fno-tracer -pedantic -Wextra -Wshadow -m64 -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o ucioption.o ucioption.cpp
g++ -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-use -fno-peel-loops -fno-tracer -pedantic -Wextra -Wshadow -m64 -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o syzygy/tbprobe.o syzygy/tbprobe.cpp
g++ -o stockfish benchmark.o bitbase.o bitboard.o endgame.o evaluate.o main.o material.o misc.o movegen.o movepick.o pawns.o position.o psqt.o search.o thread.o timeman.o tt.o uci.o ucioption.o syzygy/tbprobe.o -lgcov -m64 -Wl,--no-as-needed -lpthread -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-use -fno-peel-loops -fno-tracer -pedantic -Wextra -Wshadow -m64 -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto
make[2]: Leaving directory '/tmp/tmp4o0WoG/31m059-Stockfish-9953bff/src'
make[1]: Leaving directory '/tmp/tmp4o0WoG/31m059-Stockfish-9953bff/src'

Step 4/4. Deleting profile data ...
make ARCH=x86-64-modern COMP=gcc profileclean
make[1]: Entering directory '/tmp/tmp4o0WoG/31m059-Stockfish-9953bff/src'
make[1]: Leaving directory '/tmp/tmp4o0WoG/31m059-Stockfish-9953bff/src'

Exception running games:
Traceback (most recent call last):
  File "fishtest-master/worker/worker.py", line 91, in worker
  File "/home/fishtest/fishtest-master/worker/games.py", line 401, in run_games
    cleanup(book, testing_dir)
  File "/home/fishtest/fishtest-master/worker/games.py", line 100, in cleanup
    if not os.path.exists(os.path.join(testing_dir, book)):
NameError: global name 'book' is not defined
Task exited
Will fetch task soon...

Exception running games:
Traceback (most recent call last):
  File "fishtest-master/worker/worker.py", line 91, in worker
  File "/home/fishtest/fishtest-master/worker/games.py", line 401, in run_games
    cleanup(book, testing_dir)
  File "/home/fishtest/fishtest-master/worker/games.py", line 100, in cleanup
    if not os.path.exists(os.path.join(testing_dir, book)):
NameError: global name 'book' is not defined
Task exited

```

**Comment by Stefano80** [comment]
Hi Marco, this is strange, I just checked on master that the buggy code is not there.

Are you sure that you're using the last master?

**Comment by ppigazzini** [comment]
@marrco I forgot to inform you that you need to delete the old worker files and to reinstall the worker, sorry.

**Comment by marrco** [comment]
thanks, I'll close the issue after a successful test. (No tasks available at this time, waiting...)

**Comment by marrco** [comment]
there's still an issue, causing a loop, on a clean Debian install:

I get this message:

```
Verifying signature of stockfish ...
Verifying signature of base ...
CPU factor : 1.024523 - tc adjusted to 10.25+0.10
Running Eval vs master
['/home/fishtest/fishtest-master/worker/testing/cutechess-cli', '-repeat', '-rounds', '1000', '-tournament', 'gauntlet', '-pgnout', 'results.pgn', '-srand', '3628438437', '-resign', 'movecount=3', 'score=400', '-draw', 'movenumber=34', 'movecount=8', 'score=20', '-concurrency', '7', '-openings', u'file=2moves_v1.pgn', u'format=pgn', 'order=random', 'plies=16', '-engine', 'name=stockfish', 'cmd=stockfish', u'option.Hash=4', '-engine', 'name=base', 'cmd=base', u'option.Hash=4', '-each', 'proto=uci', 'tc=10.25+0.10', 'option.Threads=1']
('TC limit', 7318.018489156663, 'End time:', datetime.datetime(2018, 3, 29, 17, 12, 22, 16435))
/home/fishtest/fishtest-master/worker/testing/cutechess-cli: error while loading shared libraries: libQtCore.so.4: cannot open shared object file: No such file or directory
Task exited
Will fetch task soon...
(..loop..)
```
easy fixed with 
`sudo apt-get install libqtcore4`
so maybe setup instructions can add that too.

**Comment by ppigazzini** [comment]
@marrco [wiki Linux setup](https://github.com/glinscott/fishtest/wiki/Running-the-worker-on-Linux#requirements) already installs "libqtcore4"

```
sudo apt update -y
sudo apt install -y python git unzip build-essential libqtcore4 libnuma-dev
```

Glad that you are up & running :)
