### ISSUE TITLE
Error on pending user

### ISSUE THREAD

**Issue by tomtor** [glinscott/fishtest#309]
http://tests.stockfishchess.org/pending gives currently an error when selecting the single pending user.

@ppigazzini what shows the server log?

**Comment by ppigazzini** [comment]
this is the last rows:
```
2018-05-26 00:14:29,224 ERROR [waitress][Dummy-2241] Exception when serving /user/pradip
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/waitress/channel.py", line 332, in service
    task.service()
  File "/usr/lib/python2.6/site-packages/waitress/task.py", line 174, in service
    self.execute()
  File "/usr/lib/python2.6/site-packages/waitress/task.py", line 382, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/usr/lib/python2.6/site-packages/pyramid/router.py", line 251, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/usr/lib/python2.6/site-packages/pyramid/router.py", line 227, in invoke_subrequest
    response = handle_request(request)
  File "/usr/lib/python2.6/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/usr/lib/python2.6/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/usr/lib/python2.6/site-packages/pyramid/config/views.py", line 369, in rendered_view
    context)
  File "/usr/lib/python2.6/site-packages/pyramid/renderers.py", line 531, in render_view
    return self.render_to_response(response, system, request=request)
  File "/usr/lib/python2.6/site-packages/pyramid/renderers.py", line 561, in render_to_response
    result = self.render(value, system_values, request=request)
  File "/usr/lib/python2.6/site-packages/pyramid/renderers.py", line 557, in render
    result = renderer(value, system_values)
  File "/usr/lib/python2.6/site-packages/pyramid/mako_templating.py", line 240, in __call__
    reraise(MakoRenderingException(errtext), None, exc_info[2])
  File "/usr/lib/python2.6/site-packages/pyramid/mako_templating.py", line 232, in __call__
    result = template.render_unicode(**system)
  File "/usr/lib/python2.6/site-packages/mako/template.py", line 452, in render_unicode
    as_unicode=True)
  File "/usr/lib/python2.6/site-packages/mako/runtime.py", line 783, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/lib/python2.6/site-packages/mako/runtime.py", line 815, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/python2.6/site-packages/mako/runtime.py", line 841, in _exec_template
    callable_(context, *args, **kwargs)
  File "base_mak", line 42, in render_body
  File "user_mak", line 41, in render_body
MakoRenderingException:

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/pyramid/mako_templating.py", line 232, in __call__
    result = template.render_unicode(**system)
  File "/usr/lib/python2.6/site-packages/mako/template.py", line 452, in render_unicode
    as_unicode=True)
  File "/usr/lib/python2.6/site-packages/mako/runtime.py", line 783, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/lib/python2.6/site-packages/mako/runtime.py", line 815, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/python2.6/site-packages/mako/runtime.py", line 841, in _exec_template
    callable_(context, *args, **kwargs)
  File "/home/fishtest/fishtest/fishtest/fishtest/templates/base.mak", line 83, in render_body
    ${self.body()}
  File "/home/fishtest/fishtest/fishtest/fishtest/templates/user.mak", line 7, in render_body
    <label class="control-label"><a href="/tests/user/${user['username']}">${user['username']}</a></label>
TypeError: 'NoneType' object is unsubscriptable

2018-05-26 00:15:20,185 ERROR [waitress][Dummy-2290] Exception when serving /user/pradip
```

**Comment by tomtor** [comment]
@ppigazzini Strange, the user can be listed (mongodb.find) but not selected (mongodb.find_one). Another account for the same email was approved. Perhaps some unicode issue...

No major issue for now.

**Comment by tomtor** [comment]
The username had a trailing space character...
