### ISSUE TITLE
Server not stable

### ISSUE THREAD

**Issue by ppigazzini** [glinscott/fishtest#314]
In the last days the server was not stable.
I will post here the server information to debug the problem.

Fishtest logs:
[180601-nohup.out.log](https://github.com/glinscott/fishtest/files/2064816/180601-nohup.out.log)
[180602-nohup.out.log](https://github.com/glinscott/fishtest/files/2064817/180602-nohup.out.log)

```
top - 11:42:04 up  1:03,  1 user,  load average: 0.04, 0.16, 0.26
Tasks:  21 total,   1 running,  20 sleeping,   0 stopped,   0 zombie
Cpu(s): 26.1%us,  3.8%sy,  0.0%ni, 70.1%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:   3145728k total,  2982360k used,   163368k free,        0k buffers
Swap:        0k total,        0k used,        0k free,  1525192k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
  656 fishtest  20   0 36.6g 452m 359m S 66.2 14.7  11:06.02 mongod
  768 fishtest  20   0 2584m 1.2g 2360 S 23.3 41.4   3:28.17 python
    1 root      20   0 19232  692  452 S  0.0  0.0   0:00.01 init
```

```
$ free
             total       used       free     shared    buffers     cached
Mem:       3145728    2962500     183228       2564          0    1526940
-/+ buffers/cache:    1435560    1710168
Swap:            0          0          0
```

### DB
The archive tgz with the DB dump passed from 0.5 GiB to 8 GiB

### cron
```
$ time ~/fishtest/fishtest/utils/update_users.py
Successfully updated 1186 users

real    1m42.005s
user    0m57.391s
sys     0m0.806s
```

```
$ time ~/fishtest/fishtest/utils/scavenge.py

real    0m1.236s
user    0m0.348s
sys     0m0.050s
```

```
$ time ~/fishtest/fishtest/utils/purge_pgn.py
PGN runs/tasks saved:   1149/  47979
PGN runs/tasks purged: 21447/      0

real    5m13.311s
user    2m44.488s
sys     0m29.809s
```
```
$ time ~/fishtest/fishtest/utils/backup.sh
real    7m18.652s
user    6m4.469s
sys     0m50.339s
```

**Comment by tomtor** [comment]
The log is a bit big for mobile access. Could you post the last 1000 lines?

I wonder if we might have hit some IO network limit imposed by the provider eg due to up and download of PGN files?

**Comment by noobpwnftw** [comment]
Looks like MongoDB crashed?

**Comment by ppigazzini** [comment]
Yes, mongodb was not active

```
$ ps -A
  PID TTY          TIME CMD
    1 ?        00:00:00 init
    2 ?        00:00:00 kthreadd/1988
    3 ?        00:00:00 khelper/1988
  130 ?        00:00:00 udevd
  537 ?        00:00:00 rsyslogd
  564 ?        00:00:00 sshd
  575 ?        00:00:00 xinetd
  587 ?        00:00:00 saslauthd
  588 ?        00:00:00 saslauthd
  609 ?        00:00:00 sendmail
  618 ?        00:00:00 sendmail
  632 ?        00:00:00 crond
  668 ?        00:00:00 pserve
  670 tty1     00:00:00 mingetty
  671 tty2     00:00:00 mingetty
  768 ?        00:05:01 python
  781 ?        00:00:00 sshd
  802 ?        00:00:00 sshd
  803 pts/0    00:00:00 bash
 6799 pts/0    00:00:00 ps
```

**Comment by tomtor** [comment]
@vondele thanks. @ppigazzini So mongodb refuses connections. Disk full?

**Comment by ppigazzini** [comment]
@tomtor yes, the HD is filled when start the backup script
```
$ df
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/simfs      52428800 51890960    537840  99% /
none             1572864        4   1572860   1% /dev
none             1572864        0   1572864   0% /dev/shm
```

**Comment by tomtor** [comment]
@ppigazzini So we have to run the prune script with a 4 day parameter?

**Comment by ppigazzini** [comment]
@tomtor I freed some disk space from bad backups.

The backup script seems not able to upload the file to s3

```
/usr/bin/s3put:45: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
  err.message[len('No module named '):] + \
Copying /home/fishtest/backup/archive/20180602/dump.tar.gz to fishtest//backup/archive/20180602/dump.tar.gz
Traceback (most recent call last):
  File "/usr/bin/s3put", line 374, in <module>
    main()
  File "/usr/bin/s3put", line 371, in main
    headers=headers)
  File "/usr/bin/s3put", line 216, in singlepart_upload
    k.set_contents_from_filename(fullpath, *kargs, **kwargs)
  File "/usr/lib/python2.6/site-packages/boto/s3/key.py", line 1241, in set_contents_from_filename
    encrypt_key=encrypt_key)
  File "/usr/lib/python2.6/site-packages/boto/s3/key.py", line 1172, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/lib/python2.6/site-packages/boto/s3/key.py", line 710, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/usr/lib/python2.6/site-packages/boto/s3/key.py", line 882, in _send_file_internal
    query_args=query_args)
  File "/usr/lib/python2.6/site-packages/boto/s3/connection.py", line 544, in make_request
    override_num_retries=override_num_retries)
  File "/usr/lib/python2.6/site-packages/boto/connection.py", line 939, in make_request
    return self._mexe(http_request, sender, override_num_retries)
  File "/usr/lib/python2.6/site-packages/boto/connection.py", line 901, in _mexe
    raise e
socket.error: [Errno 32] Broken pipe
```

**Comment by tomtor** [comment]
> So we have to run the prune script with a 4 day parameter?

That's hard for me to judge. The original 8 day was a safe estimate based on the available free space, but we can only use halve of it, because we need extra space for the backup. To be on the safe side, we could start with 3. There is also a 20* factor for LTC:
https://github.com/glinscott/fishtest/blob/0223df5e05ea2a601f26dc5a71abe2016d3f9160/fishtest/utils/purge_pgn.py#L30
Probably better to lower that to 5*

> The backup script seems not able to upload the file to s3

Probably also related to temporary free space?

**Comment by vondele** [comment]
I'd go with some safe value. 3 days is certainly enough if somebody is eager to check.

**Comment by tomtor** [comment]
The most important are the LTC files. I would be find with 2 days for STC and 10 days for LTC.

**Comment by vondele** [comment]
fully agreed.

**Comment by ppigazzini** [comment]
@tomtor Since the 08.05.2018 the upload to s3 seems to have worked only once (the 27.05.2018), so the disk space does not seems to be the culprit.

**Comment by ppigazzini** [comment]
The server is running fine now. Thank you guys for the support!
