### ISSUE TITLE
MINGW64 (env from msys2) fishtest exception issue

### ISSUE THREAD

**Issue by d3vv** [glinscott/fishtest#328]
```
Exception running games:
Traceback (most recent call last):
  File "fishtest-master/worker/worker.py", line 122, in worker
  File "fishtest-master/worker/games.py", line 379, in run_games
  File "C:/msys64/mingw64/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 206] The filename or extension is too long: 'C:/msys64/home/dew/fishtest-master/worker/testing/fishtest-master/worker/testing/fishtest-master/worker/fishtest-master/worker/testing/fishtest-master/worker/testing/fishtest-master/worker/testing/fishtest-master/worker/fishtest-master/worker/testing'
Task exited

Exception running games:
Traceback (most recent call last):
  File "fishtest-master/worker/worker.py", line 122, in worker
  File "fishtest-master/worker/games.py", line 379, in run_games
  File "C:/msys64/mingw64/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 206] The filename or extension is too long: 'C:/msys64/home/dew/fishtest-master/worker/testing/fishtest-master/worker/testing/fishtest-master/worker/fishtest-master/worker/testing/fishtest-master/worker/testing/fishtest-master/worker/testing/fishtest-master/worker/fishtest-master/worker/testing'
Task exited

Exception running games:
Traceback (most recent call last):
  File "fishtest-master/worker/worker.py", line 122, in work

```

**Comment by RensDeVries** [comment]
It probably gives an error because the file path will be more than 256 characters long, Windows can't handle that. Though I do not understand why it makes this folder construction:
`.../fishtest-master/worker/testing/fishtest-master/worker/fishtest-master/worker/testing/...`

**Comment by ppigazzini** [comment]
@d3vv this is very old and I suppose that you have already solved the issue. I will close this issue in a week w/o your feedback.

**Comment by d3vv** [comment]
Yap! I will close an issue.
