### ISSUE TITLE
exception running games

### ISSUE THREAD

**Issue by idahabreh** [glinscott/fishtest#34]
Hi everyone,

I am trying to contribute a few cores to the tests, using 

OS X 10.9.2 (13C64) 2.3 GHz Intel Core i7 (Retina MacBook Pro)

This is what I get:

Exception running games:
Traceback (most recent call last):
  File "worker.py", line 85, in worker
    run_games(worker_info, password, remote, run, task_id)
  File "/Users/idahabreh/Downloads/fishtest-master/worker/games.py", line 477, in run_games
    launch_cutechess(*payload)
  File "/Users/idahabreh/Downloads/fishtest-master/worker/games.py", line 310, in launch_cutechess
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, universal_newlines=True, bufsize=1, close_fds=not IS_WINDOWS)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 711, in **init**
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
Task exited

Any help would be appreciated.

**Comment by protonspring** [comment]
I installed cygwin on my windows10 machine and downloaded fishtest.  When I run the worker, I get the same error.

It looks like this is because the cutechess-cli version is a linux application instead of a cygwin (cygwin doesn't run linux apps).

**Comment by protonspring** [comment]
Fixed by removing the linux binary and symlinking the windows cutechess-cli (ex. /cygdrive/c/Program Files/cutechess/cutechess-cli) to cutechess-cli in the testing folder.
