### ISSUE TITLE
Problem running fishtest on termux

### ISSUE THREAD

**Issue by nonsio28** [glinscott/fishtest#424]
I successfully installed Debian through AnLinux on my Pixel 3a and followed the instructions to run fishtest on Linux. When I run it, I get the following lines:
root@localhost:~# python fishtest-master/worker/worker.py --concurrency 6 Username Password
Worker started in /root ...
                                                        Memory: 3765624832
Worker version 69 connecting to http://tests.stockfishchess.org:80                                              Fetch task...                                           Worker version checked successfully in 0.280579s
Task requested in 0.2377s                               make: [Makefile:539: .depend] Error 1 (ignored)
                                                        Config:
debug: 'no'                                             sanitize: 'no'
optimize: 'yes'                                         arch: 'x86_64'
bits: '64'                                              kernel: 'Linux'
os: 'GNU/Linux'                                         prefetch: 'yes'                                         popcnt: 'yes'                                           sse: 'yes'
pext: 'no'                                              
Flags:                                                  CXX: g++
CXXFLAGS: -Wall -Wcast-qual -fno-exceptions -std=c++11  -pedantic -Wextra -Wshadow -m64 -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto
LDFLAGS:  -m64 -Wl,--no-as-needed -lpthread -Wall -Wcast-qual -fno-exceptions -std=c++11  -pedantic -Wextra -Wshadow -m64 -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto

Testing config sanity. If this fails, try 'make help' ...

Step 1/4. Building instrumented executable ...
make ARCH=x86-64-modern COMP=gcc gcc-profile-make
make[1]: Entering directory '/root/fishtest-master/worker/tmpfnyE8H/31m059-Stockfish-4b03be1/src'
make ARCH=x86-64-modern COMP=gcc \
EXTRACXXFLAGS='-fprofile-generate' \
EXTRALDFLAGS='-lgcov' \
all
make[2]: Entering directory '/root/fishtest-master/worker/tmpfnyE8H/31m059-Stockfish-4b03be1/src'
g++ -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-generate -pedantic -Wextra -Wshadow -m64 -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o benchmark.o benchmark.cpp
g++ -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-generate -pedantic -Wextra -Wshadow -m64 -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o bitbase.o bitbase.cpp
g++ -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-generate -pedantic -Wextra -Wshadow -m64 -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o bitboard.o bitboard.cpp
g++ -Wall -Wcast-qual -fno-exceptions -std=c++11 -fprofile-generate -pedantic -Wextra -Wshadow -m64 -DNDEBUG -O3 -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -flto   -c -o endgame.o endgame.cpp
g++: error: unrecognized command line option ‘-m64’
g++: error: unrecognized command line option ‘-msse’; did you mean ‘-fdse’?
g++: error: unrecognized command line option ‘-msse3’
g++: error: unrecognized command line option ‘-mpopcnt’
g++: error: unrecognized command line option ‘-m64’
make[2]: *** [<builtin>: bitbase.o] Error 1
make[2]: *** Waiting for unfinished jobs....
g++: error: unrecognized command line option ‘-msse’; did you mean ‘-fdse’?
g++: error: unrecognized command line option ‘-msse3’
g++: error: unrecognized command line option ‘-mpopcnt’
g++: error: unrecognized command line option ‘-m64’
g++: error: unrecognized command line option ‘-msse’; did you mean ‘-fdse’?
make[2]: *** [<builtin>: bitboard.o] Error 1
g++: error: unrecognized command line option ‘-msse3’
g++: error: unrecognized command line option ‘-mpopcnt’
make[2]: *** [<builtin>: benchmark.o] Error 1
g++: error: unrecognized command line option ‘-m64’
g++: error: unrecognized command line option ‘-msse’; did you mean ‘-fdse’?
g++: error: unrecognized command line option ‘-msse3’
g++: error: unrecognized command line option ‘-mpopcnt’
make[2]: *** [<builtin>: endgame.o] Error 1
make[2]: Leaving directory '/root/fishtest-master/worker/tmpfnyE8H/31m059-Stockfish-4b03be1/src'
make[1]: *** [Makefile:516: gcc-profile-make] Error 2
make[1]: Leaving directory '/root/fishtest-master/worker/tmpfnyE8H/31m059-Stockfish-4b03be1/src'
make: *** [Makefile:422: profile-build] Error 2

Exception running games:
Traceback (most recent call last):
  File "fishtest-master/worker/worker.py", line 128, in worker
  File "/root/fishtest-master/worker/games.py", line 405, in run_games
    setup_engine(new_engine, worker_dir, sha_new, repo_url, worker_info['concurrency'])
  File "/root/fishtest-master/worker/games.py", line 142, in setup_engine
    raise Exception('Failed to setup engine for %s' % (sha))
Exception: Failed to setup engine for 4b03be1a96730edd21edc6aa1696747d8719152c
Task exited

**Comment by ppigazzini** [comment]
@nonsio28 that mobile CPU should be too slow for fishtest so shouldn't start.

Anyway that it's an error during the Stockfish compilation
https://github.com/official-stockfish/Stockfish/blob/master/src/Makefile

Write a `custom_make.txt` alongside `worker.py`:
```
CXXFLAGS='-march=native' make -j profile-build ARCH=armv7 COMP=gcc
```

**Comment by ppigazzini** [comment]
@nonsio28 you need "cutechess-cli" for ARMv7 in "testing" folder, try searching in Raspberry Pi forum.
