### ISSUE TITLE
Exception running games

### ISSUE THREAD

**Issue by swordfish64** [glinscott/fishtest#46]
Hi all,
Tried to  run tests on XP SP3  core 2 duo T5800 cpu, but got these error:

Worker version 55 connecting to http://tests.stockfishchess.org:80
Verifying signature of stockfish.exe ...

Exception running games:
Traceback (most recent call last):
  File "D:\Documents and Settings\Ivan Trajkov\fishtest-master\worker\worker.py"
, line 86, in worker
    run_games(worker_info, password, remote, run, task_id)
  File "D:\Documents and Settings\Ivan Trajkov\fishtest-master\worker\games.py",
 line 399, in run_games
    base_nps = verify_signature(new_engine, run['args']['new_signature'], remote
, result, games_concurrency)
  File "D:\Documents and Settings\Ivan Trajkov\fishtest-master\worker\games.py",
 line 69, in verify_signature
    p = subprocess.Popen([engine, 'bench'], stderr=subprocess.PIPE, stdout=f, un
iversal_newlines=True)
  File "D:\Python27\lib\subprocess.py", line 711, in **init**
    errread, errwrite)
  File "D:\Python27\lib\subprocess.py", line 948, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 is not a valid Win32 application
Task exited

All help appreciated.

**Comment by mibere** [comment]
Maybe an issue with the spaces in "D:\Documents and Settings\Ivan Trajkov\" ?
