### ISSUE TITLE
Job in 'pending' state but active

### ISSUE THREAD

**Issue by vondele** [glinscott/fishtest#490]
The following is now the state on the main page since about 10min:

![image](https://user-images.githubusercontent.com/4202567/71770761-ea0ede00-2f30-11ea-98cd-7619183da77f.png)

bctweak~2 is in 'pending' state with assigned ~100cores

Looking at the job page, it is indeed active (ran about 2000 tests and counting since the update of the main page):

![image](https://user-images.githubusercontent.com/4202567/71770770-06127f80-2f31-11ea-8aaf-02c88c547303.png)

Note sure what the reason would be.

**Comment by tomtor** [comment]
@vondele @ppigazzini Did a restart....

Must be a semaphore issue, probably related to Python-3 migration.

**Comment by vondele** [comment]
![image](https://user-images.githubusercontent.com/4202567/71771444-2f380d80-2f3b-11ea-83ed-680f8f288ef9.png)

Now an active test with an LLR -3.51

**Comment by ppigazzini** [comment]
The logs are clean, only a request of a wrong test page since the switch to python3 (perhaps we should use a `try except` to handle this event)
```
Jan 03 22:55:31 tests.stockfishchess.org systemd[1]: Stopping Fishtest Server port 6543...
Jan 03 22:55:31 tests.stockfishchess.org systemd[1]: Stopped Fishtest Server port 6543.
Jan 03 22:56:04 tests.stockfishchess.org systemd[1]: Started Fishtest Server port 6543.
Jan 04 11:53:13 tests.stockfishchess.org systemd[1]: Stopping Fishtest Server port 6543...
Jan 04 11:53:13 tests.stockfishchess.org systemd[1]: Stopped Fishtest Server port 6543.
Jan 04 11:53:42 tests.stockfishchess.org systemd[1]: Started Fishtest Server port 6543.
Jan 04 20:35:16 tests.stockfishchess.org systemd[1]: Stopping Fishtest Server port 6543...
Jan 04 20:35:16 tests.stockfishchess.org systemd[1]: Stopped Fishtest Server port 6543.
Jan 04 20:35:16 tests.stockfishchess.org systemd[1]: Started Fishtest Server port 6543.
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]: 2020-01-04 21:46:05,044 ERROR [waitress][waitress] Exception while serving /tests/view/3227873
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]: Traceback (most recent call last):
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/tweens.py", line 13, in _error_handler
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:     response = request.invoke_exception_view(exc_info)
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/view.py", line 779, in invoke_exception_view
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:     raise HTTPNotFound
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]: pyramid.httpexceptions.HTTPNotFound: The resource could not be found.
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]: During handling of the above exception, another exception occurred:
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]: Traceback (most recent call last):
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/waitress/channel.py", line 349, in service
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:     task.service()
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/waitress/task.py", line 169, in service
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:     self.execute()
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/waitress/task.py", line 439, in execute
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:     app_iter = self.channel.server.application(environ, start_response)
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/waitress/proxy_headers.py", line 65, in translate_proxy_headers
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:     return app(environ, start_response)
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 270, in __call__
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:     response = self.execution_policy(environ, self)
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 279, in default_execution_policy
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:     return request.invoke_exception_view(reraise=True)
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/view.py", line 778, in invoke_exception_view
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:     reraise_(*exc_info)
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/compat.py", line 179, in reraise
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:     raise value
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 277, in default_execution_policy
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:     return router.invoke_request(request)
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 249, in invoke_request
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:     response = handle_request(request)
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/tweens.py", line 43, in excview_tween
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:     response = _error_handler(request, exc)
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/tweens.py", line 17, in _error_handler
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:     reraise(*exc_info)
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/compat.py", line 179, in reraise
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:     raise value
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:     response = handler(request)
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 148, in handle_request
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:     registry, request, context, context_iface, view_name
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/view.py", line 667, in _call_view
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:     response = view_callable(context, request)
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 436, in rendered_view
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:     result = view(context, request)
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 144, in _requestonly_view
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:     response = view(request)
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:   File "/home/fishtest/fishtest/fishtest/fishtest/views.py", line 861, in tests_view
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:     run = request.rundb.get_run(request.matchdict['id'])
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:   File "/home/fishtest/fishtest/fishtest/fishtest/rundb.py", line 154, in get_run
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:     run = self.runs.find_one({'_id': ObjectId(id)})
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/bson/objectid.py", line 110, in __init__
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:     self.__validate(oid)
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/bson/objectid.py", line 213, in __validate
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:     _raise_invalid_id(oid)
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/bson/objectid.py", line 40, in _raise_invalid_id
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]:     " or a 24-character hex string" % oid)
Jan 04 21:46:05 tests.stockfishchess.org pserve[10963]: bson.errors.InvalidId: '3227873' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string
```

**Comment by vondele** [comment]
Also strange, this test https://tests.stockfishchess.org/tests/view/5e10fadb5e5436dd91b27bac 
has about 350 cores assigned, yet completed games increase very slowly. (like 1 ~second, the test approved since about 40min)

**Comment by vondele** [comment]
actually same for the other recent test https://tests.stockfishchess.org/tests/view/5e10febf12ef906c8b388745

**Comment by ppigazzini** [comment]
@tomtor the `delta_update_users.py scan_all` could have introduced some inconsistency? I stopped monitoring the server after running that script.

**Comment by ppigazzini** [comment]
@vondele @tomtor I just reinstalled fishtest to add #483

**Comment by ppigazzini** [comment]
This afternoon there is an unusual low number of workers, I rebooted the server but the situation is not changed, the logs are clean.

**Comment by vondele** [comment]
I guess that's right now @noobpwnftw doing some kind of maintenance on his systems? They're slowly increasing again.

**Comment by ppigazzini** [comment]
I switched to python2 to view if this change the situation. My two workers was working fine also with python 3.

**Comment by ppigazzini** [comment]
The switch to python2 don't seems to have changed anything.

**Comment by ppigazzini** [comment]
@tomtor your 14 cores worker seems freezed in this test
https://tests.stockfishchess.org/tests/view/5e1393e6aaa74b7dfee121de

**Comment by ppigazzini** [comment]
Switched the server to python3.

**Comment by ppigazzini** [comment]
#276 merged, PROD server officially running with python3 :)
