### ISSUE TITLE
Fishtest hangs when creating a new test

### ISSUE THREAD

**Issue by snicolet** [glinscott/fishtest#510]
When using the page http://tests.stockfishchess.org/tests/run , fishtest seems to hang when we click on the "Submit" button to create a new test.

**Comment by snicolet** [comment]
More precisely, we get a 504 response after two minutes or so:

```
504 Gateway Time-out
nginx/1.14.0 (Ubuntu)
```

**Comment by ppigazzini** [comment]
From the log it should be a problem with GitHub or GitHub api.

```
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]: Traceback (most recent call last):
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/tweens.py", line 13, in _error_handler
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:     response = request.invoke_exception_view(exc_info)
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/view.py", line 779, in invoke_exception_view
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:     raise HTTPNotFound
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]: pyramid.httpexceptions.HTTPNotFound: The resource could not be found.
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]: During handling of the above exception, another exception occurred:
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]: Traceback (most recent call last):
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/waitress/channel.py", line 349, in service
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:     task.service()
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/waitress/task.py", line 169, in service
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:     self.execute()
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/waitress/task.py", line 439, in execute
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:     app_iter = self.channel.server.application(environ, start_response)
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/waitress/proxy_headers.py", line 65, in translate_proxy_headers
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:     return app(environ, start_response)
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 270, in __call__
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:     response = self.execution_policy(environ, self)
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 279, in default_execution_policy
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:     return request.invoke_exception_view(reraise=True)
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/view.py", line 778, in invoke_exception_view
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:     reraise_(*exc_info)
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/compat.py", line 179, in reraise
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:     raise value
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 277, in default_execution_policy
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:     return router.invoke_request(request)
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 249, in invoke_request
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:     response = handle_request(request)
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/tweens.py", line 43, in excview_tween
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:     response = _error_handler(request, exc)
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/tweens.py", line 17, in _error_handler
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:     reraise(*exc_info)
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/compat.py", line 179, in reraise
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:     raise value
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:     response = handler(request)
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 148, in handle_request
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:     registry, request, context, context_iface, view_name
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/view.py", line 667, in _call_view
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:     response = view_callable(context, request)
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 436, in rendered_view
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:     result = view(context, request)
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 144, in _requestonly_view
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:     response = view(request)
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:   File "/home/fishtest/fishtest/fishtest/fishtest/views.py", line 486, in tests_run
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:     return { 'args': run_args, 'tests_repo': u.get('tests_repo', ''), 'bench': get_master_bench() }
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:   File "/home/fishtest/fishtest/fishtest/fishtest/views.py", line 299, in get_master_bench
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:     for c in requests.get('https://api.github.com/repos/official-stockfish/Stockfish/commits').json():
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/requests/api.py", line 75, in get
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:     return request('get', url, params=params, **kwargs)
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/requests/api.py", line 60, in request
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:     return session.request(method=method, url=url, **kwargs)
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:     resp = self.send(prep, **send_kwargs)
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:     r = adapter.send(request, **kwargs)
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:   File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]:     raise ConnectionError(e, request=request)
Jan 16 15:14:36 tests.stockfishchess.org pserve[6147]: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/official-stockfish/Stoc
Jan 16 15:22:13 tests.stockfishchess.org pserve[6147]: 2020-01-16 15:22:13,941 ERROR [waitress][waitress] Exception while serving /tests/run

```

**Comment by tomtor** [comment]
I cannot ssh to the server at all....

**Comment by ppigazzini** [comment]
@tomtor view the edited comment

**Comment by ppigazzini** [comment]
@tomtor VPS rebooted

**Comment by snicolet** [comment]
These slowdowns often happen when the fishtest test is empty (as it has been this morning).

- Are there any tasks in the server that make external calls to GitHub api or Google api (or another site), and are more likely to be run repeatedly when the queue is empty?

- What about the workers? Could it be that they call the GitHub api more often when they are idle? downloading books or whatever?

**Comment by xoto10** [comment]
There were/are a number of machines with "Last Updated" values of 10-20 minutes, most of them using version 71:2. Perhaps they are part of the problem? If we can reject there requests quicker perhaps that would help?

**Comment by xoto10** [comment]
@tomtor @ppigazzini My impression is the server is very busy for some reason, can you guys see the cpu usage / load averages ? (obv not if you can't get in Tom!)

**Comment by ppigazzini** [comment]
@xoto10 CPU load very low (3%) RAM usage normal (33%)

**Comment by ppigazzini** [comment]
@tomtor my worker is stuck with this error

```
Verifying signature of stockfish_b8807b2e57bfc9e4539174d7518c257e81afa084.exe ...
Verifying signature of stockfish_b8807b2e57bfc9e4539174d7518c257e81afa084.exe ...
CPU factor : 0.814760 - tc adjusted to 16.30+0.16
Running asym-psq_tune vs asym-psq_tune
Fetched SPSA parameters successfully in 0.187345s
['D:\\__test_worker\\ori\\worker03\\testing\\cutechess-cli.exe', '-repeat', '-rounds', '6', '-tournament', 'gauntlet', '-site', 'https://tests.stockfishchess.org/tests/view/5e16ac760ac9162cdd5f39f0', '-event', 'Batch 207: asym-psq_tune vs asym-psq_tune', '-srand', '1073011665', '-resign', 'movecount=3', 'score=400', '-draw', 'movenumber=34', 'movecount=8', 'score=20', '-concurrency', '3', '-openings', 'file=noob_3moves.epd', 'format=epd', 'order=random', 'plies=16', '-engine', 'name=New-b8807b2', 'cmd=stockfish_b8807b2e57bfc9e4539174d7518c257e81afa084', 'option.Hash=128', 'option.nodestime=600', 'option.m::PSQT::Bonus[KNIGHT][0][0]=-167', 'option.e::PSQT::Bonus[KNIGHT][0][0]=-99', 'option.m::PSQT::Bonus[KNIGHT][0][1]=-90', 'option.e::PSQT::Bonus[KNIGHT][0][1]=-61', 'option.m::PSQT::Bonus[KNIGHT][0][2]=-81', 'option.e::PSQT::Bonus[KNIGHT][0][2]=-47', 'option.m::PSQT::Bonus[KNIGHT][0][3]=-70', 'option.e::PSQT::Bonus[KNIGHT][0][3]=-20', 'option.m::PSQT::Bonus[KNIGHT][0][4]=-69', 'option.e::PSQT::Bonus[KNIGHT][0][4]=-19', 'option.m::PSQT::Bonus[KNIGHT][0][5]=-68', 'option.e::PSQT::Bonus[KNIGHT][0][5]=-52', 'option.m::PSQT::Bonus[KNIGHT][0][6]=-95', 'option.e::PSQT::Bonus[KNIGHT][0][6]=-69', 'option.m::PSQT::Bonus[KNIGHT][0][7]=-165', 'option.e::PSQT::Bonus[KNIGHT][0][7]=-100', 'option.m::PSQT::Bonus[KNIGHT][1][0]=-81', 'option.e::PSQT::Bonus[KNIGHT][1][0]=-65', 'option.m::PSQT::Bonus[KNIGHT][1][1]=-37', 'option.e::PSQT::Bonus[KNIGHT][1][1]=-57', 'option.m::PSQT::Bonus[KNIGHT][1][2]=-29', 'option.e::PSQT::Bonus[KNIGHT][1][2]=-19', 'option.m::PSQT::Bonus[KNIGHT][1][3]=-14', 'option.e::PSQT::Bonus[KNIGHT][1][3]=6', 'option.m::PSQT::Bonus[KNIGHT][1][4]=-15', 'option.e::PSQT::Bonus[KNIGHT][1][4]=6', 'option.m::PSQT::Bonus[KNIGHT][1][5]=-27', 'option.e::PSQT::Bonus[KNIGHT][1][5]=-17', 'option.m::PSQT::Bonus[KNIGHT][1][6]=-44', 'option.e::PSQT::Bonus[KNIGHT][1][6]=-55', 'option.m::PSQT::Bonus[KNIGHT][1][7]=-82', 'option.e::PSQT::Bonus[KNIGHT][1][7]=-70', 'option.m::PSQT::Bonus[KNIGHT][2][0]=-64', 'option.e::PSQT::Bonus[KNIGHT][2][0]=-39', 'option.m::PSQT::Bonus[KNIGHT][2][1]=-18', 'option.e::PSQT::Bonus[KNIGHT][2][1]=-27', 'option.m::PSQT::Bonus[KNIGHT][2][2]=3', 'option.e::PSQT::Bonus[KNIGHT][2][2]=-9', 'option.m::PSQT::Bonus[KNIGHT][2][3]=12', 'option.e::PSQT::Bonus[KNIGHT][2][3]=26', 'option.m::PSQT::Bonus[KNIGHT][2][4]=10', 'option.e::PSQT::Bonus[KNIGHT][2][4]=29', 'option.m::PSQT::Bonus[KNIGHT][2][5]=4', 'option.e::PSQT::Bonus[KNIGHT][2][5]=-10', 'option.m::PSQT::Bonus[KNIGHT][2][6]=-16', 'option.e::PSQT::Bonus[KNIGHT][2][6]=-28', 'option.m::PSQT::Bonus[KNIGHT][2][7]=-57', 'option.e::PSQT::Bonus[KNIGHT][2][7]=-38', 'option.m::PSQT::Bonus[KNIGHT][3][0]=-38', 'option.e::PSQT::Bonus[KNIGHT][3][0]=-38', 'option.m::PSQT::Bonus[KNIGHT][3][1]=7', 'option.e::PSQT::Bonus[KNIGHT][3][1]=-3', 'option.m::PSQT::Bonus[KNIGHT][3][2]=37', 'option.e::PSQT::Bonus[KNIGHT][3][2]=12', 'option.m::PSQT::Bonus[KNIGHT][3][3]=50', 'option.e::PSQT::Bonus[KNIGHT][3][3]=27', 'option.m::PSQT::Bonus[KNIGHT][3][4]=51', 'option.e::PSQT::Bonus[KNIGHT][3][4]=29', 'option.m::PSQT::Bonus[KNIGHT][3][5]=39', 'option.e::PSQT::Bonus[KNIGHT][3][5]=15', 'option.m::PSQT::Bonus[KNIGHT][3][6]=11', 'option.e::PSQT::Bonus[KNIGHT][3][6]=-3', 'option.m::PSQT::Bonus[KNIGHT][3][7]=-37', 'option.e::PSQT::Bonus[KNIGHT][3][7]=-37', 'option.m::PSQT::Bonus[KNIGHT][4][0]=-32', 'option.e::PSQT::Bonus[KNIGHT][4][0]=-42', 'option.m::PSQT::Bonus[KNIGHT][4][1]=13', 'option.e::PSQT::Bonus[KNIGHT][4][1]=-15', 'option.m::PSQT::Bonus[KNIGHT][4][2]=47', 'option.e::PSQT::Bonus[KNIGHT][4][2]=11', 'option.m::PSQT::Bonus[KNIGHT][4][3]=51', 'option.e::PSQT::Bonus[KNIGHT][4][3]=35', 'option.m::PSQT::Bonus[KNIGHT][4][4]=52', 'option.e::PSQT::Bonus[KNIGHT][4][4]=40', 'option.m::PSQT::Bonus[KNIGHT][4][5]=49', 'option.e::PSQT::Bonus[KNIGHT][4][5]=11', 'option.m::PSQT::Bonus[KNIGHT][4][6]=14', 'option.e::PSQT::Bonus[KNIGHT][4][6]=-16', 'option.m::PSQT::Bonus[KNIGHT][4][7]=-35', 'option.e::PSQT::Bonus[KNIGHT][4][7]=-49', 'option.m::PSQT::Bonus[KNIGHT][5][0]=-8', 'option.e::PSQT::Bonus[KNIGHT][5][0]=-54', 'option.m::PSQT::Bonus[KNIGHT][5][1]=23', 'option.e::PSQT::Bonus[KNIGHT][5][1]=-42', 'option.m::PSQT::Bonus[KNIGHT][5][2]=55', 'option.e::PSQT::Bonus[KNIGHT][5][2]=-16', 'option.m::PSQT::Bonus[KNIGHT][5][3]=55', 'option.e::PSQT::Bonus[KNIGHT][5][3]=17', 'option.m::PSQT::Bonus[KNIGHT][5][4]=56', 'option.e::PSQT::Bonus[KNIGHT][5][4]=17', 'option.m::PSQT::Bonus[KNIGHT][5][5]=66', 'option.e::PSQT::Bonus[KNIGHT][5][5]=-15', 'option.m::PSQT::Bonus[KNIGHT][5][6]=23', 'option.e::PSQT::Bonus[KNIGHT][5][6]=-47', 'option.m::PSQT::Bonus[KNIGHT][5][7]=-10', 'option.e::PSQT::Bonus[KNIGHT][5][7]=-50', 'option.m::PSQT::Bonus[KNIGHT][6][0]=-67', 'option.e::PSQT::Bonus[KNIGHT][6][0]=-67', 'option.m::PSQT::Bonus[KNIGHT][6][1]=-28', 'option.e::PSQT::Bonus[KNIGHT][6][1]=-52', 'option.m::PSQT::Bonus[KNIGHT][6][2]=2', 'option.e::PSQT::Bonus[KNIGHT][6][2]=-54', 'option.m::PSQT::Bonus[K

.... several pages of parameters

T::PBonus[4][5]=0', 'option.e::PSQT::PBonus[4][5]=-7', 'option.m::PSQT::PBonus[4][6]=-12', 'option.e::PSQT::PBonus[4][6]=15', 'option.m::PSQT::PBonus[4][7]=4', 'option.e::PSQT::PBonus[4][7]=9', 'option.m::PSQT::PBonus[5][0]=-4', 'option.e::PSQT::PBonus[5][0]=30', 'option.m::PSQT::PBonus[5][1]=-13', 'option.e::PSQT::PBonus[5][1]=20', 'option.m::PSQT::PBonus[5][2]=-6', 'option.e::PSQT::PBonus[5][2]=19', 'option.m::PSQT::PBonus[5][3]=20', 'option.e::PSQT::PBonus[5][3]=30', 'option.m::PSQT::PBonus[5][4]=-10', 'option.e::PSQT::PBonus[5][4]=31', 'option.m::PSQT::PBonus[5][5]=-7', 'option.e::PSQT::PBonus[5][5]=5', 'option.m::PSQT::PBonus[5][6]=-14', 'option.e::PSQT::PBonus[5][6]=7', 'option.m::PSQT::PBonus[5][7]=-18', 'option.e::PSQT::PBonus[5][7]=12', 'option.m::PSQT::PBonus[6][0]=-7', 'option.e::PSQT::PBonus[6][0]=-3', 'option.m::PSQT::PBonus[6][1]=8', 'option.e::PSQT::PBonus[6][1]=-11', 'option.m::PSQT::PBonus[6][2]=-4', 'option.e::PSQT::PBonus[6][2]=10', 'option.m::PSQT::PBonus[6][3]=-11', 'option.e::PSQT::PBonus[6][3]=19', 'option.m::PSQT::PBonus[6][4]=3', 'option.e::PSQT::PBonus[6][4]=23', 'option.m::PSQT::PBonus[6][5]=-17', 'option.e::PSQT::PBonus[6][5]=19', 'option.m::PSQT::PBonus[6][6]=8', 'option.e::PSQT::PBonus[6][6]=3', 'option.m::PSQT::PBonus[6][7]=-6', 'option.e::PSQT::PBonus[6][7]=6', '-each', 'proto=uci', 'tc=16.30+0.16', 'timemargin=10000', 'option.Threads=1']

Exception running games:
Traceback (most recent call last):
  File "D:\__test_worker\ori\worker03\\worker.py", line 130, in worker
    pgn_file = run_games(worker_info, password, remote, run, task_id)
  File "D:\__test_worker\ori\worker03\games.py", line 563, in run_games
    task_status = launch_cutechess(cmd, remote, result, spsa_tuning, games_to_play, tc_limit * games_to_play / min(games_to_play, games_concurrency))
  File "D:\__test_worker\ori\worker03\games.py", line 389, in launch_cutechess
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, universal_newlines=True, bufsize=1, close_fds=not IS_WINDOWS)
  File "C:\msys64\mingw64\lib\python3.8\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\msys64\mingw64\lib\python3.8\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 206] The filename or extension is too long
Task exited
Traceback (most recent call last):
  File "D:\__test_worker\ori\worker03\\worker.py", line 252, in <module>
    main()
  File "D:\__test_worker\ori\worker03\\worker.py", line 248, in main
    time.sleep(HTTP_TIMEOUT)
  File "D:\__test_worker\ori\worker03\\worker.py", line 81, in on_sigint
    raise Exception('Terminated by signal')
Exception: Terminated by signal

**Comment by xoto10** [comment]
@ppigazzini 
Ok, so it's not cpu load then.
The worker I was running was getting lots of timeouts when trying to update_task, but when they were updating they were quick (~0.15s). 
Seems it may be better now??

**Comment by xoto10** [comment]
Couple of single thread normal tests running now which maybe helps. We know from the past that tunes can stress the server, maybe ~200 threads on the 20+0.2 tune wasn't helping?

**Comment by tomtor** [comment]
> Couple of single thread normal tests running now which maybe helps. We know from the past that tunes can stress the server, maybe ~200 threads on the 20+0.2 tune wasn't helping?
> Edit: i.e. the tune creates lots of network traffic

Exactly, http://tests.stockfishchess.org/tests/view/5e16ac760ac9162cdd5f39f0 has 800 parameters with a relative long name. That simply generates too much traffic when it receives many workers.

I will stop that test.

**Comment by Lolligerhans** [comment]
@tomtor It appears Windows can just not handle the arglist:
`FileNotFoundError: [WinError 206] The filename or extension is too long`

Although I should note that the problem occured long after the test in question was stopped and remedied while it was running.

**Comment by Lolligerhans** [comment]
Sometimes it seemed the server responded with "internal server error" instead of 504 Gateway Timeout. Not sure whether that helps with anything.

**Comment by xoto10** [comment]
I think there's (at least) 2 problems to find here; fishtest was struggling when there were no tests at all running (people unable to start tests), and then by chance the one test that was restarted was the big tune, which seems to have its own problems as well
