### ISSUE TITLE
python3.2

### ISSUE THREAD

**Issue by d3vv** [glinscott/fishtest#524]
```
 python3.2 fishtest/worker/worker.py
Traceback (most recent call last):
  File "fishtest/worker/worker.py", line 12, in <module>
    import requests
  File "/home/dew/fishtest/worker/requests/__init__.py", line 64, in <module>
    from .models import Request, Response, PreparedRequest
  File "/home/dew/fishtest/worker/requests/models.py", line 856
    http_error_msg = u'%s Client Error: %s for url: %s' % (self.status_code, reason, self.url)
                                                      ^
SyntaxError: invalid syntax
```

**Comment by d3vv** [comment]
```
python3.1 fishtest/worker/worker.py
Traceback (most recent call last):
  File "fishtest/worker/worker.py", line 12, in <module>
    import requests
  File "/home/dew/fishtest/worker/requests/__init__.py", line 64, in <module>
    from .models import Request, Response, PreparedRequest
  File "/home/dew/fishtest/worker/requests/models.py", line 856
    http_error_msg = u'%s Client Error: %s for url: %s' % (self.status_code, reason, self.url)
                                                      ^
SyntaxError: invalid syntax
```

**Comment by ppigazzini** [comment]
@d3vv I suppose that you are using linux, please try to install the `requests` package (e.g. `${VENV}/bin/pip install requests`) and rename the folder `fishtest/worker/requests`.

I fear that python < 3.4 could have some incompatibility, so check if your servers are able to run:
- docker (or a linux container technology like lxd/lxc): this would be the best solution
- a different python distribution, e.g. :
  - pypy: https://pypy.org/download.html
  - miniconda https://docs.conda.io/en/latest/miniconda.html
