### ISSUE TITLE
Internal Server Error when submitting tests

### ISSUE THREAD

**Issue by EterCyber** [glinscott/fishtest#654]
I setup the server according to the steps of "Fishtest server setup" on the Wiki. After the completion of the setup, the home page can be seen normally. However, when I submitted a test, the server reported an error and displayed the following information:
***********************************
Internal Server Error

The server unexpected internal server error

(generated by the waitress)
***********************************
After that, I opened fishtest_dbg.service and displayed the following information:
***********************************
pymongo.errors.OperationFailure
pymongo.errors.OperationFailure: error processing query: ns=fishtest_new.runsTree: $and
Sort: {}
Proj: {}
 planner returned error :: caused by :: hint provided does not correspond to an existing index
Traceback (most recent call last)
File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid_debugtoolbar/panels/performance.py", line 58, in resource_timer_handler
Display the sourcecode for this frameOpen an interactive python shell in this frameresult = handler(request)
File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/tweens.py", line 43, in excview_tween
Display the sourcecode for this frameOpen an interactive python shell in this frameresponse = _error_handler(request, exc)
File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/tweens.py", line 17, in _error_handler
Display the sourcecode for this frameOpen an interactive python shell in this framereraise(*exc_info)
File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/compat.py", line 179, in reraise
Display the sourcecode for this frameOpen an interactive python shell in this frameraise value
File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/tweens.py", line 41, in excview_tween
Display the sourcecode for this frameOpen an interactive python shell in this frameresponse = handler(request)
File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/router.py", line 148, in handle_request
Display the sourcecode for this frameOpen an interactive python shell in this frameregistry, request, context, context_iface, view_name
File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/view.py", line 667, in _call_view
Display the sourcecode for this frameOpen an interactive python shell in this frameresponse = view_callable(context, request)
File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 436, in rendered_view
Display the sourcecode for this frameOpen an interactive python shell in this frameresult = view(context, request)
File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pyramid/viewderivers.py", line 144, in _requestonly_view
Display the sourcecode for this frameOpen an interactive python shell in this frameresponse = view(request)
File "/home/fishtest/fishtest/fishtest/fishtest/views.py", line 882, in tests
Display the sourcecode for this frameOpen an interactive python shell in this frameraise e
File "/home/fishtest/fishtest/fishtest/fishtest/views.py", line 878, in tests
Display the sourcecode for this frameOpen an interactive python shell in this framelast_tests = homepage_results(request)
File "/home/fishtest/fishtest/fishtest/fishtest/views.py", line 841, in homepage_results
Display the sourcecode for this frameOpen an interactive python shell in this frame**get_paginated_finished_runs(request),
File "/home/fishtest/fishtest/fishtest/fishtest/views.py", line 767, in get_paginated_finished_runs
Display the sourcecode for this frameOpen an interactive python shell in this frameskip=page_idx * page_size, limit=page_size)
File "/home/fishtest/fishtest/fishtest/fishtest/rundb.py", line 344, in get_finished_runs
Display the sourcecode for this frameOpen an interactive python shell in this framecount = self.runs.estimated_document_count(hint=idx_hint)
File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pymongo/collection.py", line 1639, in estimated_document_count
Display the sourcecode for this frameOpen an interactive python shell in this framereturn self._count(cmd)
File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pymongo/collection.py", line 1600, in _count
Display the sourcecode for this frameOpen an interactive python shell in this frame_cmd, self._read_preference_for(session), session)
File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1464, in _retryable_read
Display the sourcecode for this frameOpen an interactive python shell in this framereturn func(session, server, sock_info, slave_ok)
File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pymongo/collection.py", line 1594, in _cmd
Display the sourcecode for this frameOpen an interactive python shell in this framesession=session)
File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pymongo/collection.py", line 250, in _command
Display the sourcecode for this frameOpen an interactive python shell in this frameuser_fields=user_fields)
File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pymongo/pool.py", line 613, in command
Display the sourcecode for this frameOpen an interactive python shell in this frameuser_fields=user_fields)
File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pymongo/network.py", line 167, in command
Display the sourcecode for this frameOpen an interactive python shell in this frameparse_write_concern_error=parse_write_concern_error)
File "/home/fishtest/fishtest/fishtest/env/lib/python3.6/site-packages/pymongo/helpers.py", line 159, in _check_command_response
Display the sourcecode for this frameOpen an interactive python shell in this frameraise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: error processing query: ns=fishtest_new.runsTree: $and
Sort: {}
Proj: {}
 planner returned error :: caused by :: hint provided does not correspond to an existing index
***********************************
I don't know what's wrong with my setup, it's working on the old version of fishtest, but I can't find the old version of it.

My configuration:
ubuntu: 18.04 LTS
python2: 2.7.17
python3: 3.6.9
pymongo: 3.10.1
mongodb: 4.2.6 (The older version of fishtest was configured with 4.2.3)

**Comment by tomtor** [comment]
You need to run:

https://github.com/glinscott/fishtest/blob/master/fishtest/utils/create_indexes.py

**Comment by ppigazzini** [comment]
@EterCyber run this
```
${VENV}/bin/python ${HOME}/fishtest/fishtest/utils/create_indexes.py actions flag_cache pgns runs users
```
wiki setup script fixed
