### ISSUE TITLE
Stockfish Testing after NNUE implementation

### ISSUE THREAD

**Issue by d3vv** [glinscott/fishtest#775]
I always carefully install workers, check for free CPU/Memory resources, etc.
But after NNUE implementation I have some issues:

1. Some of my workers received "Red-Residual " for tests. So I just try to reduce "concurrency-cores"..

2. Most of the workers became slow - "This machine is too slow to run fishtest effectively - sorry!"

3. Some workers has "This machine is too slow to run fishtest effectively - sorry!" message when I'm using more then 50% of cpu-cores..

4. How to use an alternative compiler (clang for example), if  `custom_make.txt` is no longer used?

**Comment by vondele** [comment]
all related to NNUE merge, and the fact that the implementation is sensitive to the hardware. However, some answers/comments:

4. no custom_make.txt is no longer supported, right now fishtest assumes gcc, in part to be able to autodetect which build is best. Very recently there was a suggestion we could do autodetection also for clang, but it would be some work to implement support for clang in the fishtest worker. The basic input is here: https://github.com/official-stockfish/Stockfish/pull/3045#issuecomment-679126992

3. If you use hyperthreaded workers, this might happen. We have plans to reduce the minimum nps for a worker. seehttps://github.com/glinscott/fishtest/pull/761 you can right now experiment with this using a manual change to the worker code.

2. See 3. Can you share which CPU model these are using (see `cat /proc/cpuinfo | grep 'model name' | uniq`)

1. The red residuals are currently ignored. Right now, they mean nothing more than 'different from most other machines on fishtest'.

**Comment by d3vv** [comment]
@vondele 

1. Are You sure that it is a good practice?
Cause "red residuals"  signaled real problems to me earlier. For example about incorrect software/hardware behavior.

2. These are really very old processors like:
`model name      : Intel(R) Core(TM)2 Quad CPU    Q6600  @ 2.40GHz`
And I don't care about it then. But they worked without complaints before.

3. IMHO "a manual change to the worker code" it is wrong approach that can skew all tests.

4. Thank You for information.

**Comment by vondele** [comment]
@d3vv well valid concerns of course. 
1) Previously we were able to more or less deal with the hardware differences, now it is much more difficult. It should become less of an issue as soon as we stop regression test against SF11. But that's what the chi2 test is measuring: are these machines equivalent. Right now, the answer is no. We can still manually purge tests, it is just not automatic anymore. T
2) The processor is capable of ssse3 so it should perform 'reasonably well' (but can't compete with avx2 and the like). The difference in performance for the NNUE evaluation is very significant, however.
3) yes, manual change is bad, we'll update that number with the next worker update.

**Comment by d3vv** [comment]
FYI: It's not possible run fishtest worker via macOS Catalina 10.15.6, Xcode Version 11.6 (11E708):
```
dew@MacBook-Pro ~ % python fishtest/worker/worker.py                             
Worker started in /Users/dew/fishtest/worker ...

Memory: 12884901888
Worker version 84 connecting to https://tests.stockfishchess.org:443
Fetch task...
API call rate limits: {u'reset': 1598315726, u'limit': 60, u'remaining': 58}
Worker version checked successfully in 0.291152s
Task requested in 0.266345s
Build uses default net:  nn-82215d0fd0df.nnue
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
clang: error: unsupported option '--help=target'
clang: error: no input files

Exception running games:
Traceback (most recent call last):
  File "fishtest/worker/worker.py", line 154, in worker
  File "/Users/dew/fishtest/worker/games.py", line 649, in run_games
    setup_engine(new_engine, worker_dir, testing_dir, remote, sha_new, repo_url, worker_info['concurrency'])
  File "/Users/dew/fishtest/worker/games.py", line 276, in setup_engine
    raise Exception('Failed to setup engine for %s' % (sha))
Exception: Failed to setup engine for c0cf7aafa20b9552d9689441b35b307475175d34
Task exited
```

```
dew@MacBook-Pro ~ % uname -a
Darwin MacBook-Pro 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
```

```
dew@MacBook-Pro ~ % clang -v
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

```
dew@MacBook-Pro ~ % g++ -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by vondele** [comment]
yes, that's because this gcc is not gcc but clang, and doesn't accept the gcc options. `clang: error: unsupported option '--help=target'

**Comment by d3vv** [comment]
@vondele Indeed, but both gcc and clang has `-march=native -### -E - < /dev/null` for flags/features investigation.

Linux example:

```
$ clang++ -march=native -### -E - < /dev/null
clang version 9.0.1 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm/9/bin
 "/usr/lib/llvm/9/bin/clang-9" "-cc1" "-triple" "x86_64-pc-linux-gnu" "-E" "-disable-free" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "-" "-mrelocation-model" "static" "-mthread-model" "posix" "-mdisable-fp-elim" "-fmath-errno" "-masm-verbose" "-mconstructor-aliases" "-munwind-tables" "-fuse-init-array" "-target-cpu" "core2" "-target-feature" "+sse2" "-target-feature" "+cx16" "-target-feature" "+sahf" "-target-feature" "-tbm" "-target-feature" "-avx512ifma" "-target-feature" "-sha" "-target-feature" "-gfni" "-target-feature" "-fma4" "-target-feature" "-vpclmulqdq" "-target-feature" "-prfchw" "-target-feature" "-bmi2" "-target-feature" "-cldemote" "-target-feature" "-fsgsbase" "-target-feature" "-ptwrite" "-target-feature" "-xsavec" "-target-feature" "-popcnt" "-target-feature" "-mpx" "-target-feature" "-aes" "-target-feature" "-avx512bitalg" "-target-feature" "-movdiri" "-target-feature" "-xsaves" "-target-feature" "-avx512er" "-target-feature" "-avx512vnni" "-target-feature" "-avx512vpopcntdq" "-target-feature" "-pconfig" "-target-feature" "-clwb" "-target-feature" "-avx512f" "-target-feature" "-clzero" "-target-feature" "-pku" "-target-feature" "+mmx" "-target-feature" "-lwp" "-target-feature" "-rdpid" "-target-feature" "-xop" "-target-feature" "-rdseed" "-target-feature" "-waitpkg" "-target-feature" "-movdir64b" "-target-feature" "-sse4a" "-target-feature" "-avx512bw" "-target-feature" "-clflushopt" "-target-feature" "-xsave" "-target-feature" "-avx512vbmi2" "-target-feature" "+64bit" "-target-feature" "-avx512vl" "-target-feature" "-invpcid" "-target-feature" "-avx512cd" "-target-feature" "-avx" "-target-feature" "-vaes" "-target-feature" "+cx8" "-target-feature" "-fma" "-target-feature" "-rtm" "-target-feature" "-bmi" "-target-feature" "-enqcmd" "-target-feature" "-rdrnd" "-target-feature" "-mwaitx" "-target-feature" "-sse4.1" "-target-feature" "-sse4.2" "-target-feature" "-avx2" "-target-feature" "+fxsr" "-target-feature" "-wbnoinvd" "-target-feature" "+sse" "-target-feature" "-lzcnt" "-target-feature" "-pclmul" "-target-feature" "-prefetchwt1" "-target-feature" "-f16c" "-target-feature" "+ssse3" "-target-feature" "-sgx" "-target-feature" "-shstk" "-target-feature" "+cmov" "-target-feature" "-avx512vbmi" "-target-feature" "-avx512bf16" "-target-feature" "-movbe" "-target-feature" "-xsaveopt" "-target-feature" "-avx512dq" "-target-feature" "-adx" "-target-feature" "-avx512pf" "-target-feature" "+sse3" "-dwarf-column-info" "-debugger-tuning=gdb" "-resource-dir" "/usr/lib/llvm/9/bin/../../../../lib/clang/9.0.1" "-internal-isystem" "/usr/local/include" "-internal-isystem" "/usr/lib/llvm/9/bin/../../../../lib/clang/9.0.1/include" "-internal-externc-isystem" "/include" "-internal-externc-isystem" "/usr/include" "-fdebug-compilation-dir" "/home/dew" "-ferror-limit" "19" "-fmessage-length" "0" "-fobjc-runtime=gcc" "-fdiagnostics-show-option" "-fcolor-diagnostics" "-o" "-" "-x" "c" "-"
```

```
$ g++ -march=native -### -E - < /dev/null
Using built-in specs.
COLLECT_GCC=g++
Target: x86_64-pc-linux-gnu
Configured with: /var/tmp/portage/sys-devel/gcc-9.3.0/work/gcc-9.3.0/configure --host=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu --prefix=/usr --bindir=/usr/x86_64-pc-linux-gnu/gcc-bin/9.3.0 --includedir=/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include --datadir=/usr/share/gcc-data/x86_64-pc-linux-gnu/9.3.0 --mandir=/usr/share/gcc-data/x86_64-pc-linux-gnu/9.3.0/man --infodir=/usr/share/gcc-data/x86_64-pc-linux-gnu/9.3.0/info --with-gxx-include-dir=/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9 --with-python-dir=/share/gcc-data/x86_64-pc-linux-gnu/9.3.0/python --enable-languages=c,c++,fortran --enable-obsolete --enable-secureplt --disable-werror --with-system-zlib --enable-nls --without-included-gettext --enable-checking=release --with-bugurl=https://bugs.gentoo.org/ --with-pkgversion='Gentoo 9.3.0 p2' --disable-esp --enable-libstdcxx-time --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --enable-multilib --with-multilib-list=m32,m64 --disable-altivec --disable-fixed-point --enable-targets=all --enable-libgomp --disable-libmudflap --disable-libssp --disable-libada --disable-systemtap --enable-vtable-verify --enable-lto --without-isl --enable-default-pie --enable-default-ssp
Thread model: posix
gcc version 9.3.0 (Gentoo 9.3.0 p2) 
COLLECT_GCC_OPTIONS='-march=native' '-E' '-shared-libgcc'
 /usr/libexec/gcc/x86_64-pc-linux-gnu/9.3.0/cc1 -E -quiet - "-march=core2" -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mno-movbe -mno-aes -mno-sha -mno-pclmul -mno-popcnt -mno-abm -mno-lwp -mno-fma -mno-fma4 -mno-xop -mno-bmi -mno-sgx -mno-bmi2 -mno-pconfig -mno-wbnoinvd -mno-tbm -mno-avx -mno-avx2 -mno-sse4.2 -mno-sse4.1 -mno-lzcnt -mno-rtm -mno-hle -mno-rdrnd -mno-f16c -mno-fsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mno-xsave -mno-xsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 -mno-clflushopt -mno-xsavec -mno-xsaves -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-avx5124fmaps -mno-avx5124vnniw -mno-clwb -mno-mwaitx -mno-clzero -mno-pku -mno-rdpid -mno-gfni -mno-shstk -mno-avx512vbmi2 -mno-avx512vnni -mno-vaes -mno-vpclmulqdq -mno-avx512bitalg -mno-movdiri -mno-movdir64b -mno-waitpkg -mno-cldemote -mno-ptwrite --param "l1-cache-size=32" --param "l1-cache-line-size=64" --param "l2-cache-size=4096" "-mtune=core2"
COMPILER_PATH=/usr/libexec/gcc/x86_64-pc-linux-gnu/9.3.0/:/usr/libexec/gcc/x86_64-pc-linux-gnu/9.3.0/:/usr/libexec/gcc/x86_64-pc-linux-gnu/:/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/:/usr/lib/gcc/x86_64-pc-linux-gnu/:/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/
LIBRARY_PATH=/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/:/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/lib/:/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-march=native' '-E' '-shared-libgcc'
```

macOS example:

```
% clang++ -march=native -### -E - < /dev/null
Apple clang version 11.0.3 (clang-1103.0.32.62)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" "-cc1" "-triple" "x86_64-apple-macosx10.15.0" "-Wdeprecated-objc-isa-usage" "-Werror=deprecated-objc-isa-usage" "-E" "-disable-free" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "-" "-mrelocation-model" "pic" "-pic-level" "2" "-mthread-model" "posix" "-mframe-pointer=all" "-fno-strict-return" "-masm-verbose" "-munwind-tables" "-target-sdk-version=10.15.6" "-target-cpu" "penryn" "-target-feature" "+sse2" "-target-feature" "+cx16" "-target-feature" "+sahf" "-target-feature" "-tbm" "-target-feature" "-avx512ifma" "-target-feature" "-sha" "-target-feature" "-gfni" "-target-feature" "-fma4" "-target-feature" "-vpclmulqdq" "-target-feature" "-prfchw" "-target-feature" "-bmi2" "-target-feature" "-cldemote" "-target-feature" "-fsgsbase" "-target-feature" "-ptwrite" "-target-feature" "-xsavec" "-target-feature" "-popcnt" "-target-feature" "-mpx" "-target-feature" "-aes" "-target-feature" "-avx512bitalg" "-target-feature" "-movdiri" "-target-feature" "-xsaves" "-target-feature" "-avx512er" "-target-feature" "-avx512vnni" "-target-feature" "-avx512vpopcntdq" "-target-feature" "-pconfig" "-target-feature" "-clwb" "-target-feature" "-avx512f" "-target-feature" "-clzero" "-target-feature" "-pku" "-target-feature" "+mmx" "-target-feature" "-lwp" "-target-feature" "-rdpid" "-target-feature" "-xop" "-target-feature" "-rdseed" "-target-feature" "-waitpkg" "-target-feature" "-movdir64b" "-target-feature" "-sse4a" "-target-feature" "-avx512bw" "-target-feature" "-clflushopt" "-target-feature" "-xsave" "-target-feature" "-avx512vbmi2" "-target-feature" "+64bit" "-target-feature" "-avx512vl" "-target-feature" "-invpcid" "-target-feature" "-avx512cd" "-target-feature" "-avx" "-target-feature" "-vaes" "-target-feature" "+cx8" "-target-feature" "-fma" "-target-feature" "-rtm" "-target-feature" "-bmi" "-target-feature" "-enqcmd" "-target-feature" "-rdrnd" "-target-feature" "-mwaitx" "-target-feature" "+sse4.1" "-target-feature" "-sse4.2" "-target-feature" "-avx2" "-target-feature" "+fxsr" "-target-feature" "-wbnoinvd" "-target-feature" "+sse" "-target-feature" "-lzcnt" "-target-feature" "-pclmul" "-target-feature" "-prefetchwt1" "-target-feature" "-f16c" "-target-feature" "+ssse3" "-target-feature" "-sgx" "-target-feature" "-shstk" "-target-feature" "+cmov" "-target-feature" "-avx512vbmi" "-target-feature" "-avx512bf16" "-target-feature" "-movbe" "-target-feature" "-xsaveopt" "-target-feature" "-avx512dq" "-target-feature" "-adx" "-target-feature" "-avx512pf" "-target-feature" "+sse3" "-dwarf-column-info" "-debugger-tuning=lldb" "-target-linker-version" "556.6" "-resource-dir" "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3" "-isysroot" "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk" "-I/usr/local/include" "-internal-isystem" "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/local/include" "-internal-isystem" "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3/include" "-internal-externc-isystem" "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include" "-internal-externc-isystem" "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include" "-Wno-objc-signed-char-bool-implicit-int-conversion" "-Wno-extra-semi-stmt" "-Wno-quoted-include-in-framework-header" "-fdebug-compilation-dir" "/Users/dew" "-ferror-limit" "19" "-fmessage-length" "165" "-stack-protector" "1" "-fstack-check" "-mdarwin-stkchk-strong-link" "-fblocks" "-fencode-extended-block-signature" "-fregister-global-dtors-with-atexit" "-fobjc-runtime=macosx-10.15.0" "-fmax-type-align=16" "-fdiagnostics-show-option" "-fcolor-diagnostics" "-o" "-" "-x" "c" "-"
```

**Comment by d3vv** [comment]
MINGW example:

```
$ g++ -march=native -### -E - < /dev/null
Using built-in specs.
COLLECT_GCC=D:\msys64\mingw32\bin\g++.exe
Target: i686-w64-mingw32
Configured with: ../gcc-10.2.0/configure --prefix=/mingw32 --with-local-prefix=/mingw32/local --build=i686-w64-mingw32 --host=i686-w64-mingw32 --target=i686-w64-mingw32 --with-native-system-header-dir=/mingw32/i686-w64-mingw32/include --libexecdir=/mingw32/lib --enable-bootstrap --with-arch=i686 --with-tune=generic --enable-languages=c,lto,c++,fortran,ada,objc,obj-c++ --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-filesystem-ts=yes --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --disable-plugin --with-libiconv --with-system-zlib --with-gmp=/mingw32 --with-mpfr=/mingw32 --with-mpc=/mingw32 --with-isl=/mingw32 --with-pkgversion='Rev1, Built by MSYS2 project' --with-bugurl=https://github.com/msys2/MINGW-packages/issues --with-gnu-as --with-gnu-ld --disable-sjlj-exceptions --with-dwarf2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.0 (Rev1, Built by MSYS2 project)
COLLECT_GCC_OPTIONS='-march=native' '-E' '-shared-libgcc'
 "D:/msys64/mingw32/lib/gcc/i686-w64-mingw32/10.2.0/cc1.exe" -E -quiet -D_REENTRANT - "-march=westmere" -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mno-movbe -maes -mno-sha -mpclmul -mpopcnt -mno-abm -mno-lwp -mno-fma -mno-fma4 -mno-xop -mno-bmi -mno-sgx -mno-bmi2 -mno-pconfig -mno-wbnoinvd -mno-tbm -mno-avx -mno-avx2 -msse4.2 -msse4.1 -mno-lzcnt -mno-rtm -mno-hle -mno-rdrnd -mno-f16c -mno-fsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mno-xsave -mno-xsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 -mno-clflushopt -mno-xsavec -mno-xsaves -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-avx5124fmaps -mno-avx5124vnniw -mno-clwb -mno-mwaitx -mno-clzero -mno-pku -mno-rdpid -mno-gfni -mno-shstk -mno-avx512vbmi2 -mno-avx512vnni -mno-vaes -mno-vpclmulqdq -mno-avx512bitalg -mno-avx512vpopcntdq -mno-movdiri -mno-movdir64b -mno-waitpkg -mno-cldemote -mno-ptwrite -mno-avx512bf16 -mno-enqcmd -mno-avx512vp2intersect --param "l1-cache-size=32" --param "l1-cache-line-size=64" --param "l2-cache-size=12288" "-mtune=westmere"
COMPILER_PATH=D:/msys64/mingw32/lib/gcc/i686-w64-mingw32/10.2.0/;D:/msys64/mingw32/lib/gcc/i686-w64-mingw32/10.2.0/;D:/msys64/mingw32/lib/gcc/i686-w64-mingw32/;D:/msys64/mingw32/lib/gcc/i686-w64-mingw32/10.2.0/;D:/msys64/mingw32/lib/gcc/i686-w64-mingw32/;D:/msys64/mingw32/lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/
LIBRARY_PATH=D:/msys64/mingw32/lib/gcc/i686-w64-mingw32/10.2.0/;D:/msys64/mingw32/lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/lib/../lib/;D:/msys64/mingw32/lib/gcc/i686-w64-mingw32/10.2.0/../../../../lib/;D:/msys64/mingw32/i686-w64-mingw32/lib/../lib/;D:/msys64/mingw32/lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/lib/;D:/msys64/mingw32/lib/gcc/i686-w64-mingw32/10.2.0/../../../;D:/msys64/mingw32/i686-w64-mingw32/lib/
COLLECT_GCC_OPTIONS='-march=native' '-E' '-shared-libgcc'
```

```
$ clang++ -march=native -### -E - < /dev/null
clang version 10.0.1 (https://github.com/Alexpux/MINGW-packages.git 94b687508346d10cec7e8c769785f73da18b4e54)
Target: x86_64-w64-windows-gnu
Thread model: posix
InstalledDir: D:\msys64\mingw64\bin
 (in-process)
 "D:\\msys64\\mingw64\\bin\\clang++.exe" "-cc1" "-triple" "x86_64-w64-windows-gnu" "-E" "-disable-free" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "-" "-mrelocation-model" "pic" "-pic-level" "2" "-mthread-model" "posix" "-mframe-pointer=none" "-fmath-errno" "-fno-rounding-math" "-masm-verbose" "-mconstructor-aliases" "-munwind-tables" "-target-cpu" "westmere" "-target-feature" "+sse2" "-target-feature" "+cx16" "-target-feature" "+sahf" "-target-feature" "-tbm" "-target-feature" "-avx512ifma" "-target-feature" "-sha" "-target-feature" "-gfni" "-target-feature" "-fma4" "-target-feature" "-vpclmulqdq" "-target-feature" "-prfchw" "-target-feature" "-bmi2" "-target-feature" "-cldemote" "-target-feature" "-fsgsbase" "-target-feature" "-ptwrite" "-target-feature" "-xsavec" "-target-feature" "+popcnt" "-target-feature" "+aes" "-target-feature" "-avx512bitalg" "-target-feature" "-movdiri" "-target-feature" "-xsaves" "-target-feature" "-avx512er" "-target-feature" "-avx512vnni" "-target-feature" "-avx512vpopcntdq" "-target-feature" "-pconfig" "-target-feature" "-clwb" "-target-feature" "-avx512f" "-target-feature" "-clzero" "-target-feature" "-pku" "-target-feature" "+mmx" "-target-feature" "-lwp" "-target-feature" "-rdpid" "-target-feature" "-xop" "-target-feature" "-rdseed" "-target-feature" "-waitpkg" "-target-feature" "-movdir64b" "-target-feature" "-sse4a" "-target-feature" "-avx512bw" "-target-feature" "-clflushopt" "-target-feature" "-xsave" "-target-feature" "-avx512vbmi2" "-target-feature" "+64bit" "-target-feature" "-avx512vl" "-target-feature" "-invpcid" "-target-feature" "-avx512cd" "-target-feature" "-avx" "-target-feature" "-vaes" "-target-feature" "+cx8" "-target-feature" "-fma" "-target-feature" "-rtm" "-target-feature" "-bmi" "-target-feature" "-enqcmd" "-target-feature" "-rdrnd" "-target-feature" "-mwaitx" "-target-feature" "+sse4.1" "-target-feature" "+sse4.2" "-target-feature" "-avx2" "-target-feature" "+fxsr" "-target-feature" "-wbnoinvd" "-target-feature" "+sse" "-target-feature" "-lzcnt" "-target-feature" "+pclmul" "-target-feature" "-prefetchwt1" "-target-feature" "-f16c" "-target-feature" "+ssse3" "-target-feature" "-sgx" "-target-feature" "-shstk" "-target-feature" "+cmov" "-target-feature" "-avx512vbmi" "-target-feature" "-avx512bf16" "-target-feature" "-movbe" "-target-feature" "-xsaveopt" "-target-feature" "-avx512dq" "-target-feature" "-adx" "-target-feature" "-avx512pf" "-target-feature" "+sse3" "-dwarf-column-info" "-debugger-tuning=gdb" "-resource-dir" "D:\\msys64\\mingw64\\lib\\clang\\10.0.1" "-internal-isystem" "D:\\msys64\\mingw64\\lib\\clang\\10.0.1\\include" "-internal-isystem" "D:\\msys64\\mingw64\\x86_64-w64-mingw32/sys-root/mingw/include" "-internal-isystem" "D:\\msys64\\mingw64\\x86_64-w64-mingw32\\include" "-internal-isystem" "D:\\msys64\\mingw64\\include" "-fdebug-compilation-dir" "D:\\msys64\\home\\dew" "-ferror-limit" "19" "-fmessage-length" "0" "-fno-use-cxa-atexit" "-fgnuc-version=4.2.1" "-fobjc-runtime=gcc" "-fseh-exceptions" "-fdiagnostics-show-option" "-faddrsig" "-o" "-" "-x" "c" "-"
```

MSYS2 example:

```
$ g++ -march=native -### -E - < /dev/null
Using built-in specs.
COLLECT_GCC=g++
Target: x86_64-pc-msys
Configured with: /msysdev/gcc/src/gcc-9.3.0/configure --build=x86_64-pc-msys --prefix=/usr --libexecdir=/usr/lib --enable-bootstrap --enable-shared --enable-shared-libgcc --enable-static --enable-version-specific-runtime-libs --with-arch=x86-64 --with-tune=generic --disable-multilib --enable-__cxa_atexit --with-dwarf2 --enable-languages=c,c++,fortran,lto --enable-graphite --enable-threads=posix --enable-libatomic --enable-libgomp --disable-libitm --enable-libquadmath --enable-libquadmath-support --disable-libssp --disable-win32-registry --disable-symvers --with-gnu-ld --with-gnu-as --disable-isl-version-check --enable-checking=release --without-libiconv-prefix --without-libintl-prefix --with-system-zlib --enable-linker-build-id --with-default-libstdcxx-abi=gcc4-compatible --enable-libstdcxx-filesystem-ts
Thread model: posix
gcc version 9.3.0 (GCC)
COLLECT_GCC_OPTIONS='-march=native' '-E' '-shared-libgcc'
 /usr/lib/gcc/x86_64-pc-msys/9.3.0/cc1.exe -E -quiet -idirafter /usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../lib/../include/w32api -idirafter /usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/lib/../lib/../../include/w32api - "-march=westmere" -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mno-movbe -maes -mno-sha -mpclmul -mpopcnt -mno-abm -mno-lwp -mno-fma -mno-fma4 -mno-xop -mno-bmi -mno-sgx -mno-bmi2 -mno-pconfig -mno-wbnoinvd -mno-tbm -mno-avx -mno-avx2 -msse4.2 -msse4.1 -mno-lzcnt -mno-rtm -mno-hle -mno-rdrnd -mno-f16c -mno-fsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mno-xsave -mno-xsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 -mno-clflushopt -mno-xsavec -mno-xsaves -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-avx5124fmaps -mno-avx5124vnniw -mno-clwb -mno-mwaitx -mno-clzero -mno-pku -mno-rdpid -mno-gfni -mno-shstk -mno-avx512vbmi2 -mno-avx512vnni -mno-vaes -mno-vpclmulqdq -mno-avx512bitalg -mno-movdiri -mno-movdir64b -mno-waitpkg -mno-cldemote -mno-ptwrite --param "l1-cache-size=32" --param "l1-cache-line-size=64" --param "l2-cache-size=12288" "-mtune=westmere"
COMPILER_PATH=/usr/lib/gcc/x86_64-pc-msys/9.3.0/:/usr/lib/gcc/x86_64-pc-msys/9.3.0/:/usr/lib/gcc/x86_64-pc-msys/:/usr/lib/gcc/x86_64-pc-msys/9.3.0/:/usr/lib/gcc/x86_64-pc-msys/:/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/
LIBRARY_PATH=/usr/lib/gcc/x86_64-pc-msys/9.3.0/:/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/lib/../lib/:/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../lib/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/lib/:/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../:/usr/lib/
COLLECT_GCC_OPTIONS='-march=native' '-E' '-shared-libgcc'
```

**Comment by snicolet** [comment]
@d3vv It would be interesting to know if you manage to install gcc10 on Catalina, and then try to run the worker again on you Macs. There are some instructions for gcc10 on Macs there: https://github.com/official-stockfish/Stockfish/commit/3542033342f15625f808013b69aa8c2d274a2f91

**Comment by ppigazzini** [comment]
1. should be improved by the new residual computation, but we need to fix the TC normalization because with NNUE is ARCH dependent
2. lowered the "slow worker" threshold
3. the "slow worker" threshold now is concurrency dependent
4. we support only gcc at the moment

BTW interesting the info on `$COMP -march=native -### -E - < /dev/null`
