### ISSUE TITLE
Worker doesn't handle passwords with % characters in them

### ISSUE THREAD

**Issue by mateon1** [glinscott/fishtest#79]
Running the worker using `python2 worker.py --concurrency 3 Username "Password%"` results in an incorrect formatting error. If the % is doubled, the formatting error does not occur, but the password is then invalid.

```
Traceback (most recent call last):
  File "worker.py", line 173, in <module>
    main()
  File "worker.py", line 136, in main
    config.set('login', 'password', args[1])
  File "/usr/lib/python2.7/ConfigParser.py", line 752, in set
    "position %d" % (value, tmp_value.find('%')))
ValueError: invalid interpolation syntax in 'Password%' at position 8
```

**Comment by Akababa** [comment]
Try manually editing the fishtest.cfg file, that worked for me.

**Comment by zungur** [comment]
The issue still persists, updated traceback with worker version 101 on Python 3.8.5. Issue stems from configparser
```
Traceback (most recent call last):
  File "a_chess/fishtest/worker/worker.py", line 514, in <module>
    main()
  File "a_chess/fishtest/worker/worker.py", line 411, in main
    config.set("login", "password", password)
  File "/usr/lib/python3.8/configparser.py", line 1201, in set
    super().set(section, option, value)
  File "/usr/lib/python3.8/configparser.py", line 894, in set
    value = self._interpolation.before_set(self, section, option,
  File "/usr/lib/python3.8/configparser.py", line 402, in before_set
    raise ValueError("invalid interpolation syntax in %r at "
ValueError: invalid interpolation syntax in 'user01%user01' at position 6
```
