### ISSUE TITLE
ValueError: No JSON object could be decoded -> Too many failed update attempts -> Task exited

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [glinscott/fishtest#92]
see the output below, my question is:

does that mean that I just wasted all those 762 calculations? or were they transmitted to your server ?

version used: Worker version 59 connecting to http://tests.stockfishchess.org:80

...
Started game 762 of 1000 (base vs stockfish)
Finished game 762 (base vs stockfish): 0-1 {Black wins by adjudication}
Score of stockfish vs base: 101 - 102 - 559  [0.499] 762

Exception from calling update_task:
Traceback (most recent call last):
  File "/erkan_yilmaz/fishtest-master/worker/games.py", line 256, in run_game
    req = requests.post(remote + '/api/update_task', data=json.dumps(result), headers={'Content-type': 'application/json'}, timeout=HTTP_TIMEOUT).json()
  File "/erkan_yilmaz/fishtest-master/worker/requests/models.py", line 604, in json
    return json.loads(self.text or self.content)
  File "/usr/lib/python2.7/json/**init**.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Started game 763 of 1000 (stockfish vs base)
Finished game 763 (stockfish vs base): 1-0 {White wins by adjudication}
Score of stockfish vs base: 102 - 102 - 559  [0.500] 763

Exception from calling update_task:
Traceback (most recent call last):
  File "/erkan_yilmaz/fishtest-master/worker/games.py", line 256, in run_game
    req = requests.post(remote + '/api/update_task', data=json.dumps(result), headers={'Content-type': 'application/json'}, timeout=HTTP_TIMEOUT).json()
  File "/erkan_yilmaz/fishtest-master/worker/requests/models.py", line 604, in json
    return json.loads(self.text or self.content)
  File "/usr/lib/python2.7/json/**init**.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Started game 764 of 1000 (base vs stockfish)
Finished game 764 (base vs stockfish): 1-0 {White wins by adjudication}
Score of stockfish vs base: 102 - 103 - 559  [0.499] 764

Exception from calling update_task:
Traceback (most recent call last):
  File "/erkan_yilmaz/fishtest-master/worker/games.py", line 256, in run_game
    req = requests.post(remote + '/api/update_task', data=json.dumps(result), headers={'Content-type': 'application/json'}, timeout=HTTP_TIMEOUT).json()
  File "/erkan_yilmaz/fishtest-master/worker/requests/models.py", line 604, in json
    return json.loads(self.text or self.content)
  File "/usr/lib/python2.7/json/**init**.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Started game 765 of 1000 (stockfish vs base)
Finished game 765 (stockfish vs base): 1/2-1/2 {Draw by adjudication}
Score of stockfish vs base: 102 - 103 - 560  [0.499] 765

Exception from calling update_task:
Traceback (most recent call last):
  File "/erkan_yilmaz/fishtest-master/worker/games.py", line 256, in run_game
    req = requests.post(remote + '/api/update_task', data=json.dumps(result), headers={'Content-type': 'application/json'}, timeout=HTTP_TIMEOUT).json()
  File "/erkan_yilmaz/fishtest-master/worker/requests/models.py", line 604, in json
    return json.loads(self.text or self.content)
  File "/usr/lib/python2.7/json/**init**.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Started game 766 of 1000 (base vs stockfish)
Finished game 766 (base vs stockfish): 1/2-1/2 {Draw by 3-fold repetition}
Score of stockfish vs base: 102 - 103 - 561  [0.499] 766

Exception from calling update_task:
Traceback (most recent call last):
  File "/erkan_yilmaz/fishtest-master/worker/games.py", line 256, in run_game
    req = requests.post(remote + '/api/update_task', data=json.dumps(result), headers={'Content-type': 'application/json'}, timeout=HTTP_TIMEOUT).json()
  File "/erkan_yilmaz/fishtest-master/worker/requests/models.py", line 604, in json
    return json.loads(self.text or self.content)
  File "/usr/lib/python2.7/json/**init**.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Started game 767 of 1000 (stockfish vs base)
Finished game 767 (stockfish vs base): 1/2-1/2 {Draw by adjudication}
Score of stockfish vs base: 102 - 103 - 562  [0.499] 767

Exception from calling update_task:
Traceback (most recent call last):
  File "/erkan_yilmaz/fishtest-master/worker/games.py", line 256, in run_game
    req = requests.post(remote + '/api/update_task', data=json.dumps(result), headers={'Content-type': 'application/json'}, timeout=HTTP_TIMEOUT).json()
  File "/erkan_yilmaz/fishtest-master/worker/requests/models.py", line 604, in json
    return json.loads(self.text or self.content)
  File "/usr/lib/python2.7/json/**init**.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Too many failed update attempts
Task exited

Exception accessing host:
Traceback (most recent call last):
  File "worker.py", line 57, in worker
    req = json.loads(req.text)
  File "/usr/lib/python2.7/json/**init**.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

....
SNIP by me -- it compiles here new versions ---
....

make[1]: Leaving directory '/tmp/tmpdw50Te/snicolet-Stockfish-eccccba/src'
Verifying signature of stockfish ...
Verifying signature of base ...
CPU factor : 0.956448 - tc adjusted to 9.56+0.10
Running supported_passer vs master
['/erkan_yilmaz/fishtest-master/worker/testing/cutechess-cli', '-repeat', '-rounds', '1000', '-tournament', 'gauntlet', '-pgnout', 'results.pgn', '-srand', '3106097062', '-resign', 'movecount=3', 'score=400', '-draw', 'movenumber=34', 'movecount=8', 'score=20', '-concurrency', '1', '-openings', u'file=2moves_v1.pgn', u'format=pgn', 'order=random', 'plies=16', '-engine', 'name=stockfish', 'cmd=stockfish', u'option.Hash=4', '-engine', 'name=base', 'cmd=base', u'option.Hash=4', '-each', 'proto=uci', 'tc=9.56+0.10', 'option.Threads=1']('TC limit', 47822.406710440104, 'End time:', datetime.datetime%282016, 10, 3, 9, 6, 7, 538090))
Indexing opening suite...
Started game 1 of 1000 (stockfish vs base)
Finished game 1 (stockfish vs base): 1-0 {White wins by adjudication}
Score of stockfish vs base: 1 - 0 - 0  [1.000] 1
Started game 2 of 1000 (base vs stockfish)
Finished game 2 (base vs stockfish): 1-0 {White wins by adjudication}
Score of stockfish vs base: 1 - 1 - 0  [0.500] 2

**Comment by joergoster** [comment]
Don't worry, results will be sent to the server almost instantly. As you can see on the fishtest page, results for a test come in continuously. In case the server is down it is possible, some (few) games are getting lost, but the worker will exit that task anyways.
