### ISSUE TITLE
Internal Server Error on http://tests.stockfishchess.org

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [glinscott/fishtest#93]
Since yesterday I got in client: (1), and the website (2) shows: (3)

(1) 
Worker version 59 connecting to http://tests.stockfishchess.org:80
Exception accessing host:
Traceback (most recent call last):
  File "worker.py", line 57, in worker
    req = json.loads(req.text)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

(2) http://tests.stockfishchess.org

(3)
Internal Server Error

The server encountered an unexpected internal server error

(generated by waitress)

**Comment by glinscott** [comment]
Server was done, apologies!  Back up now.
